#!/bin/bash
set -eu
KIT=cf
SKIP_CLEAN=${SKIP_CLEAN:-"true"}
SKIP_STABLE=${SKIP_STABLE:-"true"}
SKIP_FRESH=${SKIP_FRESH:-"false"}
SKIP_SMOKE_TESTS=${SKIP_SMOKE_TESTS:-"false"}
SKIP_DEPLOY=${SKIP_DEPLOY:-"false"}

header() {
    echo
    echo "###############################################"
    echo
    echo $*
    echo
}

cleanup() {
	for deployment in "$@"; do
	    echo "> deleting ${deployment}"
	    $BOSH -n -d "${deployment}" delete-deployment --force
	    for disk in $($BOSH disks --orphaned | grep "${deployment}" | awk '{print $1}'); do
        echo "  - removing disk $disk"
        $BOSH -n delete-disk "$disk"
	    done
	done
}

header "Checking previous deployments on ${BOSH_ENVIRONMENT}..."
$BOSH deployments

header "Cleaning up from any previous deployments (if necessary)..."a

if [[ "$SKIP_FRESH" == "false" ]]; then
  cleanup ci-baseline-${KIT}
  safe rm -rf secret/ci/baseline/${KIT}
else
  echo "Skipping FRESH"
fi

pushd dev
  CHECKED_BRANCH=$(git branch | cut -f2 -d' ')
popd

if [[ "$SKIP_STABLE" == "false" ]]; then
  header "Deploying BASELINE environment from latest STABLE release $(git tag | tail -1)"
  pushd dev
    git checkout $(git tag | tail -1)
    genesis compile-kit --name $KIT -v $(git tag | tail -1 | sed 's#^.##') --force
  popd
  genesis add-secrets ci-baseline
  genesis deploy -y ci-baseline 
else
  echo "Skipping STABLE"
fi

if [[ "$SKIP_DEPLOY" == "false" ]]; then
  header "Deploying/Upgrading to BASELINE environment FROM ${CHECKED_BRANCH}"
  pushd dev
    rm -rf *.tar.gz
    # make sure hooks are executable before screaming at shipit for failing.
    git checkout master
    genesis compile-kit --name $KIT -v 9.9.9 --force
  popd
  genesis add-secrets ci-baseline
  genesis deploy -y ci-baseline
fi

header "Validating BASELINE environment..."
if [[ "$SKIP_SMOKE_TESTS" == "false" ]]; then
    $BOSH -d ci-baseline-${KIT} run-errand smoke_tests --instance=uaa/first
else
    echo "Skipping smoke_tests"
fi

if [[ "$SKIP_CLEAN" == "false" ]]; then
  cleanup ci-baseline-${KIT}
else
  echo "Skipping CLEANUP"
fi
